using System.Collections.Generic;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace ORMTester
{
    public class AuthorRelator
    {
        public static string FetchQuery = "SELECT * FROM authors LEFT JOIN books ON books.AuthorId = authors.Id";

        private Author m_current;
        public Author Map(Author author, Book book)
        {
            if (author == null)
                return m_current;

            if (m_current != null && m_current.Id == author.Id)
            {
                m_current.Books.Add(book);
                book.Author = m_current;
                return null;
            }

            var previous = m_current;

            m_current = author;
            m_current.Books.Add(book);
            book.Author = m_current;

            return previous;
        }
    }

    [TableName("authors")]
    public class Author : IAutoGeneratedRecord
    {
        public Author()
        {
            Books = new List<Book>();
        }

        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        [Stump.ORM.Ignore]
        public List<Book> Books
        {
            get;
            set;
        }
    }
}