using System;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.AuthServer.Database.Accounts
{
    public class HardwareIdBanRelator
    {
        public static string FetchQuery = "SELECT * FROM hardwareid_bans";
        public static string FindByIP = "SELECT * FROM hardwareid_bans WHERE HardwareId={0}";
    }

    [TableName("hardwareid_bans")]
    public class HardwareIdBan : IAutoGeneratedRecord
    {
        public long Id
        {
            get;
            set;
        }

        public DateTime Date
        {
            get;
            set;
        }

        public string BanReason
        {
            get;
            set;
        }

        public int? BannedBy
        {
            get;
            set;
        }

        public string HardwareId
        {
            get;
            set;
        }
    }
}
