namespace Stump.DofusProtocol.Enums
{
    public enum ItemSuperTypeEnum
    {
        SUPERTYPE_UNKNOWN_0 = 0,
        SUPERTYPE_AMULET = 1,
        SUPERTYPE_WEAPON = 2,
        SUPERTYPE_RING = 3,
        SUPERTYPE_BELT = 4,
        SUPERTYPE_BOOTS = 5,
        SUPERTYPE_UNKNOWN_6 = 6,
        SUPERTYPE_SHIELD = 7,
        SUPERTYPE_WEAPON_8 = 8,
        SUPERTYPE_RESOURCES,
        SUPERTYPE_HAT,
        SUPERTYPE_CAPE,
        SUPERTYPE_PET,
        SUPERTYPE_DOFUS,
        SUPERTYPE_QUEST,
        SUPERTYPE_MUTATION,
        SUPERTYPE_BOOST,
        SUPERTYPE_UNKNOWN_17,
        SUPERTYPE_UNKNOWN_18,
        SUPERTYPE_UNKNOWN_19,
        SUPERTYPE_UNKNOWN_20,
        SUPERTYPE_UNKNOWN_21,
        SUPERTYPE_UNKNOWN_22,
        SUPERTYPE_COMPANION,
        SUPERTYPE_MOUNTRELATED = 24,
        SUPERTYPE_COSTUME = 25,
        SUPERTYPE_EXO_POTION = 26,
        
    }
}