namespace Stump.DofusProtocol.Enums
{
	
	public enum NotificationEnum
	{
		PERSONNAGE_NON_JOUEUR = 1,
		DÉPLACEMENT = 2,
		CHANGEMENT_DE_CARTE = 3,
		LANCER_UN_COMBAT = 4,
		PLACEMENT_EN_COMBAT = 5,
		DÉPLACEMENT_EN_COMBAT = 6,
		LANCEMENT_D_UN_SORT = 7,
		PASSER_SON_TOUR = 8,
		ECRAN_DE_FIN_DE_COMBAT = 9,
		GAIN_DE_NIVEAU = 10,
		GAIN_D_UN_NOUVEAU_SORT = 11,
		MORT_DU_PERSONNAGE = 12,
		GÉRER_SON_ÉNERGIE = 13,
		TRANSFORMATION_EN_FANTÔME = 14,
		INVENTAIRE = 15,
		CARACTÉRISTIQUES = 16,
		GRIMOIRE = 17,
		ONGLET_DES_SORTS = 18,
		ONGLET_DES_QUÊTES = 19,
		ONGLET_DE_L_ALIGNEMENT = 20,
		ONGLET_DES_MÉTIERS = 21,
		PASSAGE_EN_MODE_CRÉATURE = 22,
		REGAGNER_DES_POINTS_DE_VIE = 23,
		INFORMATION = 24,
		CHOISIR_UNE_HUMEUR = 29,
		ERREUR = 30,
		KOLIZÉUM = 33,
	}
}
