namespace Stump.DofusProtocol.Enums
{
	
	public enum OrnamentEnum
	{
		NIVEAU_100 = 13,
		NIVEAU_160 = 14,
		NIVEAU_200 = 15,
		SCORE_HONORABLE = 16,
		SCORE_RESPECTABLE = 17,
		SCORE_IMPOSANT = 18,
		EXPLORATEUR_HONORABLE = 19,
		BAROUDEUR_HONORABLE = 22,
		BAROUDEUR_RESPECTABLE = 23,
		BAROUDEUR_IMPOSANT = 24,
		BAROUDEUR_VÉNÉRABLE = 25,
		VIGILANT = 26,
		BATAILLEUR_HONORABLE = 27,
		BATAILLEUR_RESPECTABLE = 28,
		BATAILLEUR_IMPOSANT = 29,
		BATAILLEUR_VÉNÉRABLE = 30,
		BAGARREUR_IMPOSANT = 31,
		BAGARREUR_HONORABLE = 32,
		BAGARREUR_RESPECTABLE = 33,
		CHALONGEUR_HONORABLE = 34,
		CHALONGEUR_RESPECTABLE = 35,
		FLOCON_HONORABLE = 36,
		FLOCON_RESPECTABLE = 37,
		FLOCON_IMPOSANT = 38,
		AVENTURIER_RESPECTABLE = 40,
		AVENTURIER_IMPOSANT = 41,
		ARTISAN_HONORABLE = 45,
		DRAGOMAÎTRE_HONORABLE = 46,
		DRAGOMAÎTRE_RESPECTABLE = 47,
		DRAGOMAÎTRE_IMPOSANT = 48,
	}
}
