namespace Stump.DofusProtocol.Enums
{
    public enum RegionIdEnum
    {
        Amakna = 0,
        WabbitIsland = 1,
        MoonIsland = 2,
        Jail = 3,
        Tainela = 4,
        Sufokia = 5,
        TreechnidForest = 6,
        Bonta = 7,
        CaniaPlains = 8,
        Brakmar = 11,
        SidimoteMoor = 12,
        DoppleTerritory = 13,
        ImpVillage = 14,
        TroolFair = 15,
        Astrub = 18,
        NeutralPandala = 19,
        WaterPandala = 20,
        EarthPandala = 21,
        FirePandala = 22,
        AirPandala = 23,
        PandalaDungeon = 24,
        TheDragonPigsMaze = 26,
        TreechnidDungeon = 27,
        KoalakMountain = 28,
        TofuDungeon = 29,
        MinotororIsland = 30,
        LabyrinthoftheMinotoror = 31,
        LordCrowsLibrary = 32,
        CanidaeDungeon = 33,
        KoolichCavern = 34,
        SkeunksHideout = 35,
        PetSanctuary = 36,
        CracklerDungeon = 37,
        TestServer = 38,
        BworkDungeon = 39,
        ScaraleafDungeon = 40,
        FieldDungeon = 41,
        ArcticArea = 42,
        DragonPigDungeon = 43,
        DreggonDungeon = 44,
        Incarnam = 45,
        OtomaiIsland = 46,
        TheZothVillage = 47,
        TheIslandofFrigost = 48,
        SakaiIsland = 49,
        End,
    }
}